import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="fa">
      <body
        dir="rtl"
        className="max-md:pb-40 debug-screens"
      >
        <AuthProvider>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
