import type { Metadata } from "next";
import "./globals.css";
import Header from "@/component/layout/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body
        dir="rtl"
        className="flex justify-center items-center h-[1000px] bg-linear-300 from-[#5764EF] to-[#3E47AD]"
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
