import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";
import MockAutoLogin from "@/component/mockAutoLogin";
import AuthGuard from "@/component/AuthGuard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body dir="rtl" className="max-md:pb-40 debug-screens">
        {/* <MockAutoLogin /> */}
        <AuthProvider>
          {/* <AuthGuard> */}
            {children}
          {/* </AuthGuard> */}
        </AuthProvider>
      </body>
    </html>
  );
}
